#- import_playbook: harmonicio.yml

- hosts: ben-bastion
  roles:
    - bastion

- hosts: all
  roles:
    - haste-common

- hosts: ben-stream-src
  roles:
    - streaming-src

# do spark first, it installs java:

- name: spark master
  hosts: spark-master
  roles:
    - spark
    - spark-master
    - hadoop
    - hadoop-namenode
    - pyspark-notebook-server


- name: spark worker
  hosts: spark-nodes
  roles:
    - spark
    - spark-worker
    - hadoop
    - hadoop-datanode


- hosts: spark-client
  roles:
    - pyspark-notebook-server


- hosts: ben-kafka-server
  roles:
    - kafka-server
