# Setup Jupyter Notebook

- name: install python3 pip
  become: true
  package:
    name: python3-pip
    update-cache: yes

- pip:
    executable: pip3
    name: jupyter

- pip:
    executable: pip3
    name: pyspark

- pip:
    executable: pip3
    name: pandas

- pip:
    executable: pip3
    name: matplotlib



- name: create jupyter notebook dir
  file:
    path: "~/jupyter"
    state: directory

- name: create jupyter config dir
  file:
    path: "~/.jupyter"
    state: directory

# TODO: This should be git-crypted - at the moment the server only listens on localhost
- name: Config file
  copy:
    content: |
            {
              "NotebookApp": {
                "password": "sha1:f7ccd2efb957:9f4c7453468d04b867081347526e5eafc0aa63ab"
              }
            }
    dest: ~/.jupyter/jupyter_notebook_config.json

# TODO: quoting broken here?
# TODO add argument for no-browser
#- cron:
#    name: "run jupyter on startup"
#    special_time: reboot
#      job: "/usr/bin/screen -dmS jupyter sh -c \"/home/ubuntu/.local/bin/jupyter notebook --notebook-dir='/home/ubuntu/jupyter'; exec bash\""

# Note: need to reboot after running this to get the server to start.
